# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('omdan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique id for this particular property in the database', primary_key=True, serialize=False)),
                ('roomsnumber', models.DecimalField(decimal_places=2, max_digits=6)),
                ('builtarea', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('street', models.CharField(help_text='Enter Address', max_length=35)),
                ('streetnumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('surfingdate', models.DateField()),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='omdan.City')),
                ('neighborhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='omdan.Neighborhood')),
            ],
        ),
    ]
