# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omdan', '0002_surfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfer',
            name='street',
            field=models.CharField(help_text='Enter Street', max_length=35),
        ),
        migrations.AlterField(
            model_name='surfer',
            name='streetnumber',
            field=models.IntegerField(help_text='Enter Number'),
        ),
    ]
