# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omdan', '0005_auto_20171114_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
