# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omdan', '0007_auto_20171114_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(default=' ', max_length=35),
        ),
        migrations.AlterField(
            model_name='property',
            name='neighborhood',
            field=models.CharField(default=' ', max_length=35),
        ),
        migrations.AlterField(
            model_name='surfer',
            name='city',
            field=models.CharField(default=' ', max_length=35),
        ),
        migrations.AlterField(
            model_name='surfer',
            name='neighborhood',
            field=models.CharField(default=' ', max_length=35),
        ),
    ]
